In [5]:
print("Hello")

Hello


In [6]:
#install numpy
pip install numpy

SyntaxError: invalid syntax (1852718806.py, line 2)

In [8]:
#importing numpy
import numpy as np

In [9]:
list=[11,22,33,44,55]
print(list)

[11, 22, 33, 44, 55]


In [10]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [11]:
#checking version of numpy
import numpy as np
print(np.__version__)

1.26.4


In [12]:
#check type of array
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [13]:
#use tuple to create numpy array
arr2=([1,2,3,4,5,6,7])
print(arr2)
print(type(arr2))

[1, 2, 3, 4, 5, 6, 7]
<class 'list'>


#multidimentional array

In [14]:
# zero dimentional array
arr=np.array([34])
print(arr)

[34]


In [15]:
#one dimentional array
arr1=np.array([11,12,13,14,15])
print(arr1)

[11 12 13 14 15]


In [16]:
#two dimentional array
arr2=np.array([[11,12,13,14],
       [21,22,23,24]])
print(arr2)

[[11 12 13 14]
 [21 22 23 24]]


In [34]:
#three dimentional array
arr3=np.array([[[11,12,13,14],[21,22,23,24]],[[31,32,33,34,],[41,42,43,44]],[[11,12,13,14],[21,22,23,24]]])
print(arr3)

[[[11 12 13 14]
  [21 22 23 24]]

 [[31 32 33 34]
  [41 42 43 44]]

 [[11 12 13 14]
  [21 22 23 24]]]


In [26]:
#To check number of dimentions
print(arr3.ndim)

3


In [21]:
#Accessing elements
arr=np.array([20,30,40,50,60])
print(arr[4])

60


In [41]:
#Acccessing 2D array 
arr7=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row:',arr7[1,1])

2nd element on 1st row: 7


In [46]:
#Accesssing 2D array with -ve indexing
print('2nd element on 1st row:',arr7[0,-2])


2nd element on 1st row: 4


In [57]:
#Acccesssing element using slicing
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[0:5])
print(arr[0:11:2])
print(arr[1:11:2])

[1 2 3 4 5]
[1 3 5 7 9]
[ 2  4  6  8 10]


In [68]:
#Acccesssing element using -ve slicing
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[-4:-1])
print(arr[5:10:2])

[6 7 8]
[6 8]


In [83]:
#checking the data type of an array
arr=np.array([1,2,3,4,5.1,7.2])
print(arr.dtype)

float64


In [82]:
#Conversion of datatype
arr=np.array([1,2,3,4.8,5.1,6.5,7,8])
print(arr.astype(int))

[1 2 3 4 5 6 7 8]


In [86]:
#check shape of array
arr=np.array([[1,2,3,4,4],[5,6,7,8,9]])
print(arr.shape)
print(arr.size)

(2, 5)
10


In [97]:
#Reshaping array
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [98]:
#Numpy array iterating
arr=np.array([1,2,3,4])
for i in arr:
    print(i)

1
2
3
4


In [104]:
#Numpy array joining
arr1=np.array([1,1,1])
arr2=np.array([2,2,2,2])
newarr=np.concatenate((arr1,arr2))
print(newarr)

[1 1 1 2 2 2 2]


In [108]:
#Numpy splitting array
arr=np.array([1,2,3,4,5,6,7,8])
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [110]:
#Numpy searching array
arr=np.array([1,2,3,4,5,6,7])
x=np.array(arr==7)
print(x)

[False False False False False False  True]


In [124]:
#Numpy sorting array
#Descending order
arr1=np.array([3,6,4,3,0,2,1])
print(np.sort(arr1))

[0 1 2 3 3 4 6]


In [123]:
#Ascending order
arr2=np.array([8,6,7,5,4,0,4,3,2,9])
print(np.sort(arr2)[::-1])

[9 8 7 6 5 4 4 3 2 0]


In [132]:
#Numpy filter array
arr=np.array([41,42,53,44,45])
x=[True,True,False,False,True]
newarr=arr[x]
print(newarr)

[41 42 45]


In [133]:
#Creating the filter array
arr=np.array([51,52,53,54])

In [165]:
#create an empty list
filter__arr=[]

In [170]:
#go through each element in arr

if element>42:
    Filter__arr.append(True)
else:
    Filter__arr.append(False)
newarr=arr[Filter__arr]
print(Filter__arr)
print(newarr)

NameError: name 'Filter__arr' is not defined

In [182]:
#Adding and Removing elements
arr=np.array([50,60,10])
print(np.append(arr,[20,30]))
print(np.insert(arr,2,90))
print(np.delete(arr,1))

[50 60 10 20 30]
[50 60 90 10]
[50 10]


In [192]:
#Aggregating Functions
a=np.array([20,30,40,50])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.cumsum(a))

140
20
50
[ 20  50  90 140]


In [193]:
#statistical functions
import statistics as stats

In [196]:
#stats
Food_price=[99,98,97,96,95]
a=np.array(Food_price)

In [199]:
#Mean
print(np.mean(a))

97.0


In [201]:
#median
print(np.median(a))

97.0


In [209]:
#mode
Food_price=[20,30,40,50,60,70]
print(stats.mode(a))

99
